import { Button } from "@/components/ui/button";
import {
  BookOpen,
  HelpCircle,
  Mail,
  MessageSquare,
  Search,
  Shield,
  Sparkles,
  Users,
  Zap,
} from "lucide-react";
import Link from "next/link";

export const metadata = {
  title: "Help Center — Unvios",
  description:
    "Get help with Unvios. Find answers to common questions, guides, and support resources.",
  openGraph: {
    title: "Help Center — Unvios",
    description:
      "Get help with Unvios. Find answers to common questions, guides, and support resources.",
    type: "website",
    images: [
      {
        url: "/metadata-img.png",
        width: 1200,
        height: 630,
        alt: "Unvios - Your Personal Memory Assistant",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Help Center — Unvios",
    description:
      "Get help with Unvios. Find answers to common questions, guides, and support resources.",
    images: ["/metadata-img.png"],
  },
};

export default function HelpCenterPage() {
  const faqs = [
    {
      category: "Getting Started",
      icon: <Sparkles className="w-5 h-5" />,
      questions: [
        {
          q: "How do I create my first memory?",
          a: "You can create memories by chatting with Unvios in the dashboard. Simply type or speak naturally, and Unvios will extract and save important information automatically.",
        },
        {
          q: "What types of information can I save?",
          a: "Unvios can save any personal information: facts about yourself, preferences, goals, meeting notes, ideas, tasks, and more. The AI automatically tags and organizes everything.",
        },
        {
          q: "How do I search my memories?",
          a: "Use the chat interface to ask questions in natural language. Unvios uses AI to find relevant memories and provide contextual answers based on what you've saved.",
        },
      ],
    },
    {
      category: "Privacy & Security",
      icon: <Shield className="w-5 h-5" />,
      questions: [
        {
          q: "How is my data protected?",
          a: "All memories are encrypted at rest and in transit. We use industry-standard encryption and never share your data with third parties. You maintain full ownership of your information.",
        },
        {
          q: "Can I export or delete my data?",
          a: "Yes! You can export all your memories as JSON at any time from your account settings. You can also permanently delete your account and all associated data.",
        },
        {
          q: "Where is my data stored?",
          a: "Your data is stored in secure, SOC 2 compliant data centers. We use PostgreSQL with pgvector for efficient and secure storage of your memories and embeddings.",
        },
      ],
    },
    {
      category: "Features & Capabilities",
      icon: <Zap className="w-5 h-5" />,
      questions: [
        {
          q: "What is the memory format?",
          a: "Memories are saved with content, tags, and optional embeddings for semantic search. The AI automatically extracts structured information from your conversations.",
        },
        {
          q: "How does AI-powered recall work?",
          a: "Unvios uses vector embeddings to find semantically similar memories, even if they don't match your exact words. This enables intelligent, context-aware recall.",
        },
        {
          q: "Can I organize memories with tags?",
          a: "Yes! Tags are automatically generated by the AI, but you can also manually add, edit, or remove tags to customize organization to your needs.",
        },
        {
          q: "What LLM providers are supported?",
          a: "Unvios supports OpenAI and any OpenAI-compatible API endpoint. You can configure your preferred provider in your environment settings.",
        },
      ],
    },
    {
      category: "Account & Billing",
      icon: <Users className="w-5 h-5" />,
      questions: [
        {
          q: "Is there a free plan?",
          a: "Yes! We offer a free tier that includes core memory features. Premium plans add advanced capabilities like unlimited memories, enhanced AI models, and priority support.",
        },
        {
          q: "How do I upgrade my plan?",
          a: "Visit the Pricing page and select your desired plan. Billing is handled securely through Stripe, and you can upgrade or downgrade at any time.",
        },
        {
          q: "Can I cancel my subscription?",
          a: "Yes, you can cancel anytime from your account settings. You'll retain access to premium features until the end of your billing period.",
        },
      ],
    },
  ];

  const guides = [
    {
      title: "Quick Start Guide",
      desc: "Get up and running with Unvios in 5 minutes",
      icon: <BookOpen className="w-6 h-6" />,
      href: "/help#quickstart",
    },
    {
      title: "Memory Best Practices",
      desc: "Learn how to capture and organize memories effectively",
      icon: <Sparkles className="w-6 h-6" />,
      href: "/help#best-practices",
    },
    {
      title: "API Documentation",
      desc: "Integrate Unvios into your own applications",
      icon: <Zap className="w-6 h-6" />,
      href: "/help#api",
    },
    {
      title: "Privacy & Security Guide",
      desc: "Understand how we protect your data",
      icon: <Shield className="w-6 h-6" />,
      href: "/security",
    },
  ];

  return (
    <main className="bg-white">
      {/* Header */}
      <section className="py-16 bg-gradient-to-b from-orange-50 to-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-orange-100 rounded-full text-orange-700 text-sm font-medium mb-6">
            <HelpCircle className="w-4 h-4" />
            Help Center
          </div>
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            How can we help you?
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto mb-8">
            Find answers to common questions, explore guides, and get the most
            out of Unvios.
          </p>

          {/* Search Box */}
          <div className="max-w-2xl mx-auto">
            <div className="relative">
              <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
              <input
                type="text"
                placeholder="Search for help..."
                className="w-full pl-12 pr-4 py-4 rounded-full border-2 border-gray-200 focus:border-orange-500 focus:outline-none text-gray-900"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Quick Links */}
      <section className="py-12 border-b border-gray-200">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {guides.map((guide) => (
              <Link
                key={guide.title}
                href={guide.href}
                className="group bg-white border-2 border-gray-200 rounded-xl p-6 hover:border-orange-500 hover:shadow-lg transition-all"
              >
                <div className="w-12 h-12 rounded-full bg-orange-100 flex items-center justify-center group-hover:bg-orange-500 transition-colors mb-4">
                  <div className="text-orange-600 group-hover:text-white transition-colors">
                    {guide.icon}
                  </div>
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  {guide.title}
                </h3>
                <p className="text-sm text-gray-600">{guide.desc}</p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* FAQs by Category */}
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Frequently Asked Questions
            </h2>
            <p className="text-lg text-gray-600">
              Browse answers by category or use the search above
            </p>
          </div>

          <div className="space-y-12">
            {faqs.map((category) => (
              <div key={category.category}>
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-full bg-orange-100 flex items-center justify-center text-orange-600">
                    {category.icon}
                  </div>
                  <h3 className="text-2xl font-bold text-gray-900">
                    {category.category}
                  </h3>
                </div>

                <div className="space-y-6">
                  {category.questions.map((item) => (
                    <div
                      key={item.q}
                      className="bg-gray-50 rounded-xl p-6 border border-gray-200"
                    >
                      <h4 className="text-lg font-semibold text-gray-900 mb-3">
                        {item.q}
                      </h4>
                      <p className="text-gray-600 leading-relaxed">{item.a}</p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact Support */}
      <section className="py-16 bg-gradient-to-b from-white to-orange-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white border-2 border-orange-200 rounded-2xl p-8 md:p-12 text-center">
            <div className="w-16 h-16 rounded-full bg-orange-100 flex items-center justify-center mx-auto mb-6">
              <MessageSquare className="w-8 h-8 text-orange-600" />
            </div>
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Still need help?
            </h2>
            <p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto">
              Can't find what you're looking for? Our support team is here to
              help you get the most out of Unvios.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/contact">
                <Button
                  size="lg"
                  className="bg-orange-600 text-white px-8 py-6 rounded-full"
                >
                  <Mail className="mr-2 h-5 w-5" />
                  Contact Support
                </Button>
              </Link>
              <a href="mailto:support@unvios.app">
                <Button
                  size="lg"
                  variant="outline"
                  className="px-8 py-6 rounded-full"
                >
                  <MessageSquare className="mr-2 h-5 w-5" />
                  Email Us
                </Button>
              </a>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
